### PR TITLE
fix README image and improve Travis build

### PR DESCRIPTION
**Pull request by armish**
Improvements over #2. Sorry these changes got left out from the previous PR.

### CODE REVIEW

**Comment by timodonnell** [comment]
I wonder if the pyensembl data download will work in travis? Let's see...

**Comment by armish** [comment]
That's what Alex and Tavi are doing for their builds, so I am optimistic; but you never know ;)

**Comment by armish** [comment]
Looks like everything went fine with the Python 2.x tests, but the tests failed on Python 3.x due to backwards-incompatible stuff: https://travis-ci.org/hammerlab/varlens/builds/93808240

Dropping the Python 3.x test for now. We will soon get the green light from Travis :+1:

**Comment by timodonnell** [comment]
Cool, I'll take a shot at a quick fix for Python 3

**Comment by armish** [comment]
Cool, we got the green light — merging this one in :+1:

**Pull request merged**
